title: Lunar Store Guidelines
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://mattgamer6660.github.io/test/

aux_links:
  Game: https://www.roblox.com/games/14782345660/Untitled-Game
  
color_scheme: dark

callouts:
  warning:
    color: red
